import 'package:flutter/material.dart';
import 'package:healthink/pages/menu_page.dart';

class FoodMenu {
  static Map<int, Map<String, FoodMenuBody>> menu = {
    1: {
      "chicken": FoodMenuBody(variants: {
        'crispy': FoodMenu(
          category: 1,
          calories: 166,
          protein: 20.8,
          carbs: 0,
          fats: 8.6,
          iron: 1.02,
          zinc: 0,
          b12: 0,
          price: 50,
        ),
        'fillet': FoodMenu(
          category: 1,
          calories: 133,
          protein: 21.2,
          carbs: 0,
          fats: 2.4,
          iron: 0.71,
          zinc: 0,
          b12: 0,
          price: 50,
        ),
      }, image: const AssetImage('assets/edibles/crispy_chicken.jpg')),
      "pork": FoodMenuBody(variants: {
        'katsudon': FoodMenu(
          category: 1,
          calories: 208.6,
          protein: 12.4,
          carbs: 0,
          fats: 17.3,
          iron: 0.7,
          zinc: 0,
          b12: 0,
          price: 50,
        ),
        'porkchop': FoodMenu(
          category: 1,
          calories: 193,
          protein: 21.5,
          carbs: 0,
          fats: 11.2,
          iron: 0.7,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
      }, image: const AssetImage('assets/edibles/pork.jpg')),
      "silog": FoodMenuBody(variants: {
        'sisilog': FoodMenu(
          category: 1,
          calories: 352,
          protein: 21.27,
          carbs: 5.49,
          fats: 18.43,
          iron: 2.48,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
        'longsilog': FoodMenu(
          category: 1,
          calories: 329,
          protein: 17.0,
          carbs: 9.3,
          fats: 24.98,
          iron: 1.83,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
        'hamsilog': FoodMenu(
          category: 1,
          calories: 108,
          protein: 10.5,
          carbs: 1.0,
          fats: 6.5,
          iron: 1.0,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
        'tosilog': FoodMenu(
          category: 1,
          calories: 136,
          protein: 10,
          carbs: 5.3,
          fats: 8.0,
          iron: 0.73,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
        'tunasilog': FoodMenu(
          category: 1,
          calories: 159,
          protein: 12,
          carbs: 2.3,
          fats: 11,
          iron: 0.73,
          zinc: 0,
          b12: 0.6,
          price: 55,
        ),
        'corn silog': FoodMenu(
          category: 1,
          calories: 159,
          protein: 10,
          carbs: 2.3,
          fats: 11,
          iron: 2.73,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
        'tapsilog': FoodMenu(
          category: 1,
          calories: 189.7,
          protein: 21,
          carbs: 0.9,
          fats: 10.7,
          iron: 1.0,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
        'bacon silog': FoodMenu(
          category: 1,
          calories: 220,
          protein: 17,
          carbs: 0.9,
          fats: 16,
          iron: 1.0,
          zinc: 0,
          b12: 0.6,
          price: 55,
        ),
      }, image: const AssetImage('assets/edibles/silog.jpg')),
      "3pc siomai": FoodMenuBody(variants: {
        'no rice': FoodMenu(
          category: 1,
          calories: 95,
          protein: 6,
          carbs: 7,
          fats: 5,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
        'w/ rice': FoodMenu(
          category: 1,
          calories: 300,
          protein: 10.3,
          carbs: 52,
          fats: 5.4,
          iron: 1.9,
          zinc: 0,
          b12: 0,
          price: 35,
        ),
      }, image: const AssetImage('assets/edibles/siomai.jpg')),
      "lumpia shanghai": FoodMenuBody(variants: {
        '3 pcs': FoodMenu(
          category: 1,
          calories: 105,
          protein: 6,
          carbs: 10,
          fats: 4,
          iron: 0.4,
          zinc: 0,
          b12: 0,
          price: 20,
        ),
      }, image: const AssetImage('assets/edibles/lumpia shanghai.jpg')),
      "ngohiong": FoodMenuBody(variants: {
        '1 pc': FoodMenu(
          category: 1,
          calories: 62,
          protein: 2.7,
          carbs: 8.7,
          fats: 1.9,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 15,
        ),
      }, image: const AssetImage('assets/edibles/ngohiong.jpg')),
      "steamed rice": FoodMenuBody(variants: {
        'w/ siomai': FoodMenu(
          category: 1,
          calories: 498,
          protein: 23,
          carbs: 36.3,
          fats: 27.7,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 55,
        ),
      }, image: const AssetImage('assets/edibles/steamed rice.jpg')),
      "burp burger": FoodMenuBody(variants: {
        'regular': FoodMenu(
          category: 1,
          calories: 159,
          protein: 5.3,
          carbs: 20.5,
          fats: 7.3,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
        'super': FoodMenu(
          category: 1,
          calories: 268,
          protein: 13.2,
          carbs: 21.3,
          fats: 15.4,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 50,
        ),
      }, image: const AssetImage('assets/edibles/burger.png')),
      "sandwich": FoodMenuBody(variants: {
        'egg': FoodMenu(
          category: 1,
          calories: 213,
          protein: 10.2,
          carbs: 28.3,
          fats: 5.9,
          iron: 2.7,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
        'ham': FoodMenu(
          category: 1,
          calories: 203,
          protein: 10.7,
          carbs: 28.7,
          fats: 4.4,
          iron: 2.3,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
      }, image: const AssetImage('assets/edibles/sandwich.jpg')),
      "hotdog": FoodMenuBody(variants: {
        'no bun': FoodMenu(
          category: 1,
          calories: 109,
          protein: 5,
          carbs: 1,
          fats: 8.7,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
        'w/ bun': FoodMenu(
          category: 1,
          calories: 210,
          protein: 8,
          carbs: 19,
          fats: 9.8,
          iron: 1,
          zinc: 0,
          b12: 0,
          price: 35,
        ),
      }, image: const AssetImage('assets/edibles/hotdog.jpeg')),
      "sweet corn": FoodMenuBody(variants: {
        'regular': FoodMenu(
          category: 1,
          calories: 62,
          protein: 2.3,
          carbs: 13.7,
          fats: 0.9,
          iron: 0.4,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
      }, image: const AssetImage('assets/edibles/sweet corn.jpg')),
      "squid roll": FoodMenuBody(variants: {
        '3 pcs': FoodMenu(
          category: 1,
          calories: 67,
          protein: 7,
          carbs: 6,
          fats: 2.6,
          iron: 0.8,
          zinc: 0,
          b12: 0,
          price: 30,
        ),
      }, image: const AssetImage('assets/edibles/squid roll.jpg')),
      "squid ball": FoodMenuBody(variants: {
        '3 pcs': FoodMenu(
          category: 1,
          calories: 100.1,
          protein: 9,
          carbs: 9,
          fats: 3,
          iron: 0.5,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
      }, image: const AssetImage('assets/edibles/squid ball.jpg')),
      "tempura": FoodMenuBody(variants: {
        '3 pcs': FoodMenu(
          category: 1,
          calories: 56,
          protein: 5,
          carbs: 2,
          fats: 3.2,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 20,
        ),
      }, image: const AssetImage('assets/edibles/tempura.jpg')),
    },
    2: {
      "water": FoodMenuBody(variants: {
        '500 ml': FoodMenu(
          category: 2,
          calories: 0,
          protein: 0,
          carbs: 0,
          fats: 0,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 20,
        ),
        '1 liter': FoodMenu(
          category: 2,
          calories: 0,
          protein: 0,
          carbs: 0,
          fats: 0,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 30,
        ),
      }, image: const AssetImage('assets/edibles/water.jpg')),
      "milo": FoodMenuBody(variants: {
        '12 oz': FoodMenu(
          category: 2,
          calories: 184.6,
          protein: 5.3,
          carbs: 29.8,
          fats: 4.6,
          iron: 6.4,
          zinc: 0,
          b12: 1.4,
          price: 30,
        ),
        '16 oz': FoodMenu(
          category: 2,
          calories: 246,
          protein: 7.1,
          carbs: 39.7,
          fats: 6.1,
          iron: 8.5,
          zinc: 0,
          b12: 1.9,
          price: 40,
        ),
      }, image: const AssetImage('assets/edibles/milo.jpg')),
      "nescafe": FoodMenuBody(variants: {
        '12 oz': FoodMenu(
          category: 2,
          calories: 115,
          protein: 0,
          carbs: 20,
          fats: 3.5,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 30,
        ),
        '16 oz': FoodMenu(
          category: 2,
          calories: 154,
          protein: 0,
          carbs: 27,
          fats: 4.7,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 40,
        ),
      }, image: const AssetImage('assets/edibles/nescafe.png')),
      "nestea": FoodMenuBody(variants: {
        '12 oz': FoodMenu(
          category: 2,
          calories: 35,
          protein: 2,
          carbs: 9,
          fats: 0,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
        '16 oz': FoodMenu(
          category: 2,
          calories: 47,
          protein: 2,
          carbs: 12,
          fats: 0,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 30,
        ),
      }, image: const AssetImage('assets/edibles/nestea.jpg')),
      "lemonade": FoodMenuBody(variants: {
        '12 oz': FoodMenu(
          category: 2,
          calories: 167,
          protein: 0,
          carbs: 44,
          fats: 0.2,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 25,
        ),
        '16 oz': FoodMenu(
          category: 2,
          calories: 223,
          protein: 0,
          carbs: 59,
          fats: 0.3,
          iron: 0,
          zinc: 0,
          b12: 0,
          price: 30,
        ),
      }, image: const AssetImage('assets/edibles/lemonade.jpg')),
    }
  };

  final int category;
  final double calories, price, protein, carbs, fats, iron, zinc, b12;

  FoodMenu(
      {required this.category,
      required this.calories,
      required this.protein,
      required this.carbs,
      required this.fats,
      required this.iron,
      required this.zinc,
      required this.b12,
      required this.price});
}
